CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208155118_InitialModels') THEN
    CREATE TABLE "AndroidNotifications" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DeviceToken" character varying(50) NOT NULL,
        "Message" character varying(2000) NOT NULL,
        "Title" character varying(255) NOT NULL,
        "Condition" character varying(2000) NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "ProcessedAt" timestamp with time zone NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_AndroidNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208155118_InitialModels') THEN
    CREATE TABLE "IosNotifications" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PushToken" character varying(50) NOT NULL,
        "Alert" character varying(2000) NOT NULL,
        "Priority" integer NOT NULL DEFAULT 10,
        "IsBackground" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "ProcessedAt" timestamp with time zone NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_IosNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208155118_InitialModels') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220208155118_InitialModels', '6.0.1');
    END IF;
END $EF$;
COMMIT;

